### ISSUE TITLE
`spicy-protocol-analyzer` doesn't build.

### ISSUE THREAD

**Issue by J-Gras** [zeek/package-template#20]
Using the template to create a new protocol analyzer does not work as expected:
```
$ zkg --user create --template https://github.com/zeek/package-template --version v2.0.0 --features spicy-protocol-analyzer --packagedir spicy-template-test
...
$ mkdir build && cd build && cmake ..
$ make
[ 50%] Compiling Template analyzer
error: PCH file uses an older PCH format that is no longer supported
1 error generated.
error: PCH file uses an older PCH format that is no longer supported
1 error generated.
error: PCH file uses an older PCH format that is no longer supported
1 error generated.
error: PCH file uses an older PCH format that is no longer supported
1 error generated.
error: PCH file uses an older PCH format that is no longer supported
1 error generated.
[error] <Spicy Plugin for Zeek>: JIT compilation failed
make[2]: *** [spicy-modules/template.hlto] Error 1
make[1]: *** [analyzer/CMakeFiles/Template.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by bbannier** [comment]
The precompiled headers the compiler is complaining about are not built by default and only generated if a user calls `spicy-precompile-headers`. The are stored on a per-user basis in `$HOME/.cache/spicy/<VERSION>`.

The issue here seems to be that the Zeek version and/or C++ compiler used by Spicy have changed since they were generated. Could you please remove and regenerate them @J-Gras? I will close this issue for now, please reopen if you still see it after refreshing the precompiled headers.
